import { Data } from './data';

export const FORTUNEDATA: Data[] = [
    {"id": 1, "value": "Today you will inspire others with laughter."},
    {"id": 2, "value": "You are wise beyond your years, don't let it go to waste."},
    {"id": 3, "value": "You will reunite with an old friend soon."},
    {"id": 4, "value": "An exotic adventure is on the horizon."},
    {"id": 5, "value": "You will be very successful at work this month."},
    {"id": 6, "value": "Someone passionate about you will help you out when you need it."},
    {"id": 7, "value": "Relax a little, you are working way too hard."},
    {"id": 8, "value": "Enjoy the little things in life, you will be surprised in their effect."},
    {"id": 9, "value": "Be sure to eat fruit this week, it will make you healthy."},
    {"id": 10, "value": "You may not like the advice you hear from a loved one, but it will help you out.  Take it."},
    {"id": 11, "value": "Bad luck and misfortune will forever torment your pathetic soul for all eternity."},
    {"id": 12, "value": "You will find happiness with a new love."},
    {"id": 13, "value": "Proper diet and exercise will help you out more than you think."},
    {"id": 14, "value": "You will get a promotion at work a week from now."},
    {"id": 15, "value": "Be on the lookout for something special in the mail."},
    {"id": 16, "value": "Keep up the effort in your studies.  You're on your way to greatness."},
    {"id": 17, "value": "Your four favorite things today will be flour, sugar, vanilla and oil.  Remember that."},
    {"id": 18, "value": "Life is like a box of chocolates.  Be careful which one you take."},
    {"id": 19, "value": "A nice walk in your neighborhood will help relieve your stress."},
    {"id": 20, "value": "You know that chance you've wanted to take?  Today's a good day to take that chance."},
    {"id": 21, "value": "You will impress someone with your infectious humor and heart."},
    {"id": 22, "value": "You should find some extra time to please your spouse or loved one."},
    {"id": 23, "value": "It's important that you listen to what you're being told; it will push you to greatness."},
    {"id": 24, "value": "This weekend would be a good time to take a moment and meditate.  It will help you clear your mind."},
    {"id": 25, "value": "Music is the key to happiness, take a moment to embrace the message."},
    {"id": 26, "value": "If you have any major problems to fix, now would be a good time to fix them."},
    {"id": 27, "value": "Reach out to someone from your past.  You may be surprised by how much they can inspire you."},
    {"id": 28, "value": "Don't spend all day watching the TV, go outside and get some fresh air."},
    {"id": 29, "value": "Take an extra look at your work.  Sometimes it's best to make sure it's done correctly."},
    {"id": 30, "value": "If you're feeling down, find someone to hug."},
    {"id": 31, "value": "Bring an extra sweater when you're out in the cold.  It will help you stay warm."},
    {"id": 32, "value": "Always carry sunscreen wherever you go.  The sun can be deadly."},
    {"id": 33, "value": "Take a drive to Delaware if you can.  You'll be amazed."},
    {"id": 34, "value": "Listen to your pet.  Not just physically but emotionally.  You'll be impressed."},
    {"id": 35, "value": "The value of a hard earned penny is more than the value of the penny itself.  Cherish it."},
    {"id": 36, "value": "Don't judge a book by its cover, you'll understand why when presented with an interesting situation."},
    {"id": 37, "value": "It never hurts to stand outside for a few minutes and look at the stars."},
    {"id": 38, "value": "The only thing stopping you from having a perfect day is not smiling.  Put on your best smile."},
    {"id": 39, "value": "It never hurts to speak up, even if you think it's a stupid question."},
    {"id": 40, "value": "Try something new today.  The adventures it can lead to in the future are endless."},
    {"id": 41, "value": "Better days are ahead, don't let your obstacles overpower you."},
    {"id": 42, "value": "Why fly when you can enjoy the open road."},
    {"id": 43, "value": "It's never too late to fix a situation that's been bothering you for a while."},
    {"id": 44, "value": "It takes two to tango, remember that the next time someone wants you to do all the work."},
    {"id": 45, "value": "If life is getting you down, remember that other people have it more rough than you."},
    {"id": 46, "value": "Life is too short to dwell on negative things.  Enjoy yourself."},
    {"id": 47, "value": "One man's trash is another person's treasure.  Remember that the next time you want to throw something in the trash."},
    {"id": 48, "value": "It never hurts to double-check your work, or to have someone check it for you."},
    {"id": 49, "value": "Helping someone out who needs it will not only benefit them, but make you feel like you've made a difference."},
    {"id": 50, "value": "Recycling is good for the earth, and good for the soul."},
    {"id": 51, "value": "Time flies when you're having fun.  Cherish every moment of it."},
    {"id": 52, "value": "Now is a good time to clean out your closet.  There's nothing wrong with a little organization."},
    {"id": 53, "value": "Just because it's raining outside doesn't mean you can't have any fun."},
    {"id": 54, "value": "Why don't you take a minute and enjoy your morning coffee or tea."},
    {"id": 55, "value": "When trouble calls, don't panic and be sure to consider all your options."},
    {"id": 56, "value": "Sometimes it's just nice to relax at home and watch the rain."},
    {"id": 57, "value": "Your life will be so much better when everything is organized."},
    {"id": 58, "value": "It's good to make a mistake once in a while.  That way you will learn not to repeat it."},
    {"id": 59, "value": "Always show respect for your competition.  You will be rewarded by your respect in the long run."},
    {"id": 60, "value": "Don't be afraid of what you don't know.  New experiences are good for the soul."},
    {"id": 61, "value": "Keep your friends close and your enemies closer."},
    {"id": 62, "value": "Having an easy night at home is nice once in a while.  Don't make your life too hectic."},
    {"id": 63, "value": "The next time you feel bad about yourself, remember there are people dealing with far worse."},
    {"id": 64, "value": "Your intelligence will help you get out of touch situations."},
    {"id": 65, "value": "There's always a challenge worth pursuing.  Go for it."},
    {"id": 66, "value": "If something keeps breaking down, it's time to move on and replace it."},
    {"id": 67, "value": "As long as your memories are pure, any loved one you may have lost is never lost."},
    {"id": 68, "value": "The one thing money can't buy is pure happiness."},
    {"id": 69, "value": "Real friends treat you unconditionally with love and respect."},
    {"id": 70, "value": "Learning from histories greatest mistakes will help you avoid repeating them."},
    {"id": 71, "value": "Solving problems together is a sign of strength, not weakness."},
    {"id": 72, "value": "You will make someone feel appreciated today."},
    {"id": 73, "value": "Your work week will be filled with lots of challenges and problems to deal with, but your intelligence will get you through them."},
    {"id": 74, "value": "Good news is around the corner.  Don't give up hope."},
    {"id": 75, "value": "It doesn't hurt to apologize to someone you hurt in the past.  Clearing your conscience will also make you feel better."},
    {"id": 76, "value": "Never underestimate the power of love."},
    {"id": 77, "value": "If you feel like someone has taken control of your life, others are there to help."},
    {"id": 78, "value": "Don't feel threatened by those who appear superior.  Embrace the challenge."},
    {"id": 79, "value": "You can make a difference.  Speak up if you feel something is not right."},
    {"id": 80, "value": "Don’t focus on small issues.  Choose your battles wisely."},
    {"id": 81, "value": "Don’t encourage bad behavior, even if you feel that you’re outnumbered."},
    {"id": 82, "value": "Your life is not in someone else’s control.  You have the power to make a change for the better."},
    {"id": 83, "value": "This week would be a great time to donate blood."},
    {"id": 84, "value": "Resilience should be your theme of the month at home and at work."},
    {"id": 85, "value": "Your life is not in danger.  Don’t feel threatened by anyone or anything."},
    {"id": 86, "value": "Eating too much is never a good idea, but physically and mentally."},
    {"id": 87, "value": "Always make sure to spend at least 30 minutes a day to reflect."},
    {"id": 88, "value": "You will be at your best when you slow down and make sure you’re making the right choice."},
    {"id": 89, "value": "Consider going somewhere you've never thought of going.  You may be surprised."},
    {"id": 90, "value": "Whenever you don’t feel loved or just need a hug when no one's around, give a tree a hug."},
    {"id": 91, "value": "The key to life is having a healthy balance.  Too much of anything can cause problems."},
    {"id": 92, "value": "The next time you squish a bug, just remember.  It has a purpose in this world."},
    {"id": 93, "value": "When life is hard for you, take a step back and re-evaluate the problem."},
    {"id": 94, "value": "The toughest decisions in life are also the most rewarding."},
    {"id": 95, "value": "Your humbleness will get you rewarded when you least expect it."},
    {"id": 96, "value": "Sometimes the easiest solution is to restart the thought process."},
    {"id": 97, "value": "Gaining experience doesn't require having all the talent."},
    {"id": 98, "value": "There's nothing wrong with sucking at something at first. Don't get discouraged."},
    {"id": 99, "value": "Too get to the top, you must start at the bottom."},
    {"id": 100, "value": "In some instances, all you need is chance to succeed."}    
]